# Generated by Django 5.1 on 2024-09-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
