# Generated by Django 5.0.6 on 2024-09-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='username',
            field=models.CharField(default='anonymous', max_length=150),
        ),
    ]
